import Head from "next/head";
//import { Client } from 'appwrite';
//import Link from "next/link";

// const client = new Client();

// client
//     .setEndpoint('https://cloud.appwrite.io/v1')
//     .setProject('64b4936c3134104fc96e');

export default function Home() {

  return (
    <>
      <Head>
        <title>Naberus Games</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/logo.ico" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff"></meta>
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(280,100%,70%)]">Naberus Games</span>
          </h1>
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            <span className="text-[hsl(300,100%,70%)]">Coming Soon</span>
          </h1>
          <p className="text-2xl text-white">
            Being made with ♥️ from The Naberus Games Team
          </p>
        </div>
      </main>
    </>
  );
}
